#!/usr/bin/with-contenv sh

if [ ! -f /data/adbkey ] ; then
  echo "Generating ADB key"
  adb keygen /data/adbkey
fi

echo "Starting ADB server on port $ADB_SERVER_PORT"
adb -P $ADB_SERVER_PORT -a server nodaemon 2>&1 >/dev/null | grep -v "^adb I"
